### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by EdenRochman** [jasmcaus/caer#11]
import caer

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-343221543dc2a4> in <module>
----> 1 import caer

~/QWE/ASD/ZXC/FGH/VBN/caer/__init__.py in <module>
     70 
     71 # Preprocessing
---> 72 from .preprocess import (
     73     preprocess_from_dir,
     74     sep_train,

~/QWE/ASD/ZXC/FGH/VBN/caer/preprocess.py in <module>
     16 
     17 from .utilities import get_classes_from_dir, to_array
---> 18 from .io import imread
     19 from .preprocessing import MeanProcess
     20 from ._internal import _check_target_size, _check_mean_sub_values

~/QWE/ASD/ZXC/FGH/VBN/caer/io.py in <module>
     11 
     12 
---> 13 import cv2 as cv
     14 from urllib.request import urlopen
     15 

~/QWE/ASD/ZXC/FGH/VBN/cv2/__init__.py in <module>
      3 import sys
      4 
----> 5 from .cv2 import *
      6 from .data import *
      7 

ModuleNotFoundError: No module named 'cv2.cv2'

**Comment by jasmcaus** [comment]
Hi @EdenRochman! Thanks for this. 

It's too early to pinpoint the error, but this is most likely due to an older version of OpenCV. Can you confirm the versions of `caer` and `cv2` that you're using and whether upgrading to the latest version helps?

**Comment by EdenRochman** [comment]
I just upgraded to the latest version of both while I was trying to use the package.

**Comment by jasmcaus** [comment]
Okay, does this happen when you import `cv2`  standalone?

**Comment by EdenRochman** [comment]
I fixed by uninstalling numpy, scipy, matplotlib, scikit-learn, jupyter and opencv-python and installing them again.

**Comment by jasmcaus** [comment]
Ah, that's great! Wonder why you got the error. I doubt it was `caer`-specific, but I'm glad it's fixed.
I'm closing the issue now. Feel free to open it if need be. 
Thanks 👍🏻
