### ISSUE TITLE
[Feat] Add support for the LUV colorspace in `caer.color`

### ISSUE THREAD

**Issue by jasmcaus** [jasmcaus/caer#21]
Add support for the LUV colorspace in `caer.color`

Open for contributions :)

**Comment by jasmcaus** [comment]
@lucasace if you'd like to work on this PR ^

**Comment by jasmcaus** [comment]
@lucasace will you be working on this?

**Comment by lucasace** [comment]
I would work on this, but i cant for some time, therefore dont want to be assigned to it right now
Ill notify you once i can

**Comment by jasmcaus** [comment]
Fixed by @lucasace in #48
