### ISSUE TITLE
imsave function does not return status

### ISSUE THREAD

**Issue by zigiiprens** [jasmcaus/caer#4]
## 🚀 caer,imsave
For your release, in `caer.io.imsave` function, you can see that the function does not return any status.

## Motivation

See that opencv already return status, we can integrate the status with some personal control.

![Screenshot from 2020-12-02 12-50-31](https://user-images.githubusercontent.com/29894513/100856957-1f071600-349d-11eb-846d-4c6c3d76630a.png)

**Comment by jasmcaus** [comment]
Thanks for your PR. This change will reflect in the next release of `caer`
