### ISSUE TITLE
caer.preprocess_from_dir() Error: File "C:\Python38\lib\site-packages\caer\preprocess.py

### ISSUE THREAD

**Issue by amandacassar** [jasmcaus/caer#5]
Hi,
I am trying out your code for face recognition using Tensorflow's implementation of Keras.  I am having an issue when creating the training data, with the following line:
"train = caer.preprocess_from_dir(...)" 

As datasets, I have several folders with 10-16 images in each folder.  And in the previous lines of code everything worked fine but when I am trying to train the images, it is processing only 3 images of the first folder (which contains 16 images).  It is processing the last 3 images of the first folder, then it crashes.

The error is as follows:
File "C:\Python38\lib\site-packages\caer\preprocess.py", line 132, in preprocess_from_dir for image_path in img_list:
TypeError: 'NoneType' object is not iterable

Thanks

**Comment by jasmcaus** [comment]
Hi @amandacassar! Thanks for this. For a bit more context, could you do the following:

Which version of Caer are you currently on? If you're not on `v1.9.3`, could you upgrade to the latest version (you may use this command: `pip install --upgrade caer`) and verify if the issue still exists?

If it still doesn't work, we may need to perform additional troubleshooting to isolate this.

**Comment by amandacassar** [comment]
Hi @jasmcaus 
Thank you for your prompt reply!  I upgraded caer and that fixed the issue :)
Thanks a lot

**Comment by jasmcaus** [comment]
Ah, I'm glad the issue was fixed. Happy to help :)

Closing this issue now. Feel free to open it if need be.
