### ISSUE TITLE
ValueError: verbose flag must be either 1 (display progress to terminal) or 0 otherwise

### ISSUE THREAD

**Issue by meet1919** [jasmcaus/caer#69]
I am learning OpenCV and at first, I saw the youtube video from freecodecamp [OpenCv Course by Jason Dzousa](https://www.youtube.com/watch?v=oXlwWbU8l2o) In the last video the line:
 `train = caer.preprocess_from_dir(char_path, characters, IMG_SIZE, channels, isShuffle=True)` 
throws the error: 
`ValueError: verbose flag must be either 1 (display progress to terminal) or 0 otherwise`
I can't understand why this error comes.

**Comment by meet1919** [comment]
@jasmcaus

**Comment by jasmcaus** [comment]
Can you confirm the version of `caer` you're using? Use `caer.__version__`

**Comment by meet1919** [comment]
> Can you confirm the version of `caer` you're using? Use `caer.__version__`

I used kaggle to install as described in the youtube video, so it would be the latest version of caer.

**Comment by jasmcaus** [comment]
Thanks for spotting this. I've released a new version `2.0.0`. It should be fixed.

**Comment by meet1919** [comment]
Thanks for the support. Now it works like a Charm :-)

**Comment by jasmcaus** [comment]
Great to hear! Good luck with the course :)
