### ISSUE TITLE
AttributeError: module 'caer' has no attribute 'normalize'

### ISSUE THREAD

**Issue by meet1919** [jasmcaus/caer#70]
Hey sorry to bother again. I upgraded caer to 2.0.1 
I proceeded but again 
`from tensorflow.keras.utils import to_categorical`
--> `featureSet = caer.normalize(featureSet)`
`labels = to_categorical(labels, len(characters))`

the second line throws an error.
`AttributeError: module 'caer' has no attribute 'normalize'`

**Comment by jasmcaus** [comment]
Good catch! I made sweeping changes to the codebase recently. Should have checked if it had broken anything. `v2.0.2` should solve your problem.

**Comment by meet1919** [comment]
Yes everything is fixed. Thank you
